# Generated by Django 2.1.12 on 2019-10-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Closed')], default='pending', max_length=8),
        ),
    ]
