# Generated by Django 3.1.7 on 2021-02-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191003_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Closed')], default='active', max_length=8),
        ),
    ]
